name: Deploy FE
on:
  push:
    branches:
      - release-2.1
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install & Build
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
          NEXT_PUBLIC_STREAM_API_KEY: ${{ secrets.NEXT_PUBLIC_STREAM_API_KEY }}
          NEXT_STREAM_API_SECRET_KEY: ${{ secrets.NEXT_STREAM_API_SECRET_KEY }}
          NEXT_ELEVENLABS_API_KEY: ${{ secrets.NEXT_ELEVENLABS_API_KEY }}
          NEXT_GEMINI_API_KEY: ${{ secrets.NEXT_GEMINI_API_KEY }}
        run: |
          npm install
          npm run build

      - name: Copy .next to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: ".next/,public/,package.json,next.config.js"
          target: "/home/ubuntu/productivity-plogg-client/"

      - name: Install deps & Restart PM2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/productivity-plogg-client
            npm install --omit=dev
            pm2 restart plog-frontend --update-env